version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    versioning-strategy: increase
    open-pull-requests-limit: 100
    reviewers:
      - 'boyka-core'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Calcutta'
    groups:
      major:
        update-types: ['major']
      minor:
        update-types: ['minor']
      patch:
        update-types: ['patch']
