name: Label Feature and Bug PRs

on:
  pull_request:
    branches:
      - main
    types:
      - closed
      - opened

concurrency:
  group: boyka-cli-labeler-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
